In [1]:
import torch
import numpy as np

TENSOR BASICS

In [2]:
#create empty tensor
x = torch.empty(2,2,3)
x

tensor([[[5.6165e-36, 1.4013e-45, 4.6271e-36],
         [1.4013e-45, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])

In [3]:
#create tensor with random values
x = torch.rand(2,2)
x

tensor([[0.4387, 0.4977],
        [0.9680, 0.7840]])

In [4]:
#create tensor with zeros
x = torch.zeros(2,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
#change dtype
print(x.dtype)
x = torch.ones(2,2,dtype = torch.float16)
print(x.dtype)

torch.float32
torch.float16


In [6]:
#tensor from list
x = torch.tensor([[1,2],[3,4]],dtype = torch.int32)
x

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

BASIC OPERATIONS

In [7]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)


tensor([[0.2019, 0.2153],
        [0.2784, 0.5035]])
tensor([[0.7150, 0.3092],
        [0.7707, 0.5096]])


In [8]:
#addition
z = x+y
z

tensor([[0.9168, 0.5245],
        [1.0491, 1.0130]])

In [9]:
#addition
z = torch.add(x,y)
z

tensor([[0.9168, 0.5245],
        [1.0491, 1.0130]])

In [10]:
#inplace addition
y.add_(x)   #any operation with a trailing _ to it will perform an inplace operation 
y

tensor([[0.9168, 0.5245],
        [1.0491, 1.0130]])

In [11]:
print(x)
print(y)

tensor([[0.2019, 0.2153],
        [0.2784, 0.5035]])
tensor([[0.9168, 0.5245],
        [1.0491, 1.0130]])


In [12]:
#elementwise multiplication
# z = x*y     #option 1
z = torch.mul(x,y)    #option 2
# y.mul_(x)      #option 3
z

tensor([[0.1851, 0.1129],
        [0.2921, 0.5100]])

In [13]:
#elementwise division
# z = x/y 
z = torch.div(x,y)
# x.div_(y)
z

tensor([[0.2202, 0.4104],
        [0.2653, 0.4970]])

In [14]:
#slicing operation

x = torch.rand(5,3)
print(x)

print(x[:,0]) #get all rows and one column
print(x[1,:]) #print only second rows and all columns


tensor([[0.9868, 0.5148, 0.4322],
        [0.8470, 0.7862, 0.1733],
        [0.4390, 0.4127, 0.5117],
        [0.5544, 0.5588, 0.6165],
        [0.6842, 0.4643, 0.5697]])
tensor([0.9868, 0.8470, 0.4390, 0.5544, 0.6842])
tensor([0.8470, 0.7862, 0.1733])


In [15]:
#using .item() function
#can only be used if there is only one element present in the tensor

print(x[1,1])
print(x[1][1])
print(x[1,1].item())

tensor(0.7862)
tensor(0.7862)
0.7861897945404053


In [17]:
#reshaping a tensor
x = torch.rand(2,8)
print(x)
y = x.view(16)
print(y)

tensor([[0.2701, 0.8896, 0.4624, 0.4554, 0.5906, 0.6656, 0.8782, 0.3793],
        [0.5236, 0.5190, 0.6098, 0.0125, 0.8534, 0.3534, 0.5347, 0.5391]])
tensor([0.2701, 0.8896, 0.4624, 0.4554, 0.5906, 0.6656, 0.8782, 0.3793, 0.5236,
        0.5190, 0.6098, 0.0125, 0.8534, 0.3534, 0.5347, 0.5391])


In [18]:
x = torch.rand(4,4)
print(x)

y = x.view(2,8)
print(y)

#use of -1 in view

y = x.view(-1,8)
print(y)

y = x.view(8,-1)
print(y)
print(y.size())  #use of size() function

tensor([[3.6172e-02, 3.5374e-01, 4.7535e-04, 7.9182e-02],
        [2.2118e-01, 4.8868e-01, 9.9496e-02, 7.9454e-01],
        [4.7668e-01, 4.2740e-01, 2.0374e-02, 6.4046e-01],
        [6.9062e-01, 7.8397e-01, 6.7725e-01, 2.3400e-01]])
tensor([[3.6172e-02, 3.5374e-01, 4.7535e-04, 7.9182e-02, 2.2118e-01, 4.8868e-01,
         9.9496e-02, 7.9454e-01],
        [4.7668e-01, 4.2740e-01, 2.0374e-02, 6.4046e-01, 6.9062e-01, 7.8397e-01,
         6.7725e-01, 2.3400e-01]])
tensor([[3.6172e-02, 3.5374e-01, 4.7535e-04, 7.9182e-02, 2.2118e-01, 4.8868e-01,
         9.9496e-02, 7.9454e-01],
        [4.7668e-01, 4.2740e-01, 2.0374e-02, 6.4046e-01, 6.9062e-01, 7.8397e-01,
         6.7725e-01, 2.3400e-01]])
tensor([[3.6172e-02, 3.5374e-01],
        [4.7535e-04, 7.9182e-02],
        [2.2118e-01, 4.8868e-01],
        [9.9496e-02, 7.9454e-01],
        [4.7668e-01, 4.2740e-01],
        [2.0374e-02, 6.4046e-01],
        [6.9062e-01, 7.8397e-01],
        [6.7725e-01, 2.3400e-01]])
torch.Size([8, 2])


In [19]:
#torch to numpy array
a = torch.ones(4)
print(a)
b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1.])
[1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [20]:
#changing the tensor also changes the numpy array i.e. both share the same memory - only applicable on CPU
a.add_(1)
print(a)
print(b)


tensor([2., 2., 2., 2.])
[2. 2. 2. 2.]


In [21]:
#Requires Grad - Argument given to instruct that the gradients for the variable might be needed later
#by default, requres_grad is False
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


AUTOGRAD

Autograd: This class is an engine to calculate derivatives (Jacobian-vector product to be more precise). It records a graph of all the operations performed on a gradient enabled tensor and creates an acyclic graph called the dynamic computational graph. The leaves of this graph are input tensors and the roots are output tensors. Gradients are calculated by tracing the graph from the root to the leaf and multiplying every gradient in the way using the chain rule.


For each backpropagation iteration, several gradients are calculated and something called a computation graph is built for storing these gradient functions. PyTorch does it by building a Dynamic Computational Graph (DCG). This graph is built from scratch in every iteration providing maximum flexibility to gradient calculation. For example, for a forward operation (function)Mul a backward operation (function) called MulBackwardis dynamically integrated in the backward graph for computing the gradient.

--------------------------------------REFERENCES--------------------------------------------
                                                   
https://towardsdatascience.com/pytorch-autograd-understanding-the-heart-of-pytorchs-magic-2686cd94ec95
                                   
https://www.youtube.com/watch?v=hjnVLfvhN0Q&t=1334


In [25]:
x = torch.rand(3, requires_grad=True)
print(x)
y = x+2
print(y)
z = y*y*2
z = z.mean()
print(z)
z.backward()
x.grad

tensor([0.1363, 0.0730, 0.7197], requires_grad=True)
tensor([2.1363, 2.0730, 2.7197], grad_fn=<AddBackward0>)
tensor(10.8386, grad_fn=<MeanBackward0>)


tensor([2.8484, 2.7640, 3.6263])

In [32]:
gen = torch.Generator().manual_seed(1)
x = torch.rand(3,generator=gen,requires_grad=True)
print(x)
y = x+2
print(y)
z = y*y*2
z = z.mean()
print(z)
z.backward()
m = x.grad
m 

tensor([0.7576, 0.2793, 0.4031], requires_grad=True)
tensor([2.7576, 2.2793, 2.4031], grad_fn=<AddBackward0>)
tensor(12.3830, grad_fn=<MeanBackward0>)


tensor([3.6768, 3.0391, 3.2041])

In [33]:
gen = torch.Generator().manual_seed(1)
x = torch.rand(3,generator=gen,requires_grad=True)
print(x)
y = x+2
print(y)
z = y*y*2
z = z.sum()
print(z)
z.backward()
n = x.grad
n 

tensor([0.7576, 0.2793, 0.4031], requires_grad=True)
tensor([2.7576, 2.2793, 2.4031], grad_fn=<AddBackward0>)
tensor(37.1491, grad_fn=<SumBackward0>)


tensor([11.0305,  9.1172,  9.6123])

In [34]:
n/m

tensor([3.0000, 3.0000, 3.0000])

In [35]:
#calculating gradient by manually entering the v vector
gen = torch.Generator().manual_seed(1)
x = torch.rand(3,requires_grad=True,generator=gen)
print(x)
y = x+2
print(y)
z = y*y*2
print(z)
v = torch.tensor([1.,1.,1.])
z.backward(v) #entering the value of v vector to be multiplied by transpose of Jacobian matrix
print(x.grad)


tensor([0.7576, 0.2793, 0.4031], requires_grad=True)
tensor([2.7576, 2.2793, 2.4031], grad_fn=<AddBackward0>)
tensor([15.2091, 10.3905, 11.5495], grad_fn=<MulBackward0>)
tensor([11.0305,  9.1172,  9.6123])


In [36]:
#Prevent variable from tracking gradients
x = torch.rand(3,requires_grad=True)
print(x)

# x.requires_grad_(False)
# x.detach()
# with torch.no_grad():



tensor([0.0084, 0.3482, 0.1844], requires_grad=True)


In [37]:
x.requires_grad_(False)
print(x)

tensor([0.0084, 0.3482, 0.1844])


In [38]:
x = torch.rand(3,requires_grad=True)
print(x)
y = x.detach()
print(y)

tensor([0.4681, 0.3365, 0.9736], requires_grad=True)
tensor([0.4681, 0.3365, 0.9736])


In [39]:
x = torch.rand(3,requires_grad=True)
print(x)
y = x+2
print(y)
with torch.no_grad():
    y = x+2
    print(y)

tensor([0.6457, 0.4528, 0.9915], requires_grad=True)
tensor([2.6457, 2.4528, 2.9915], grad_fn=<AddBackward0>)
tensor([2.6457, 2.4528, 2.9915])


In [40]:
#Gradients are added up in backend
#They need to be cleared up using grad.zero_()
#An example:

x = torch.ones(4,requires_grad=True)
print(x)

for epoch in range(3):
    y = 3*x
    y = y.sum()
    y.backward()
    print(x.grad)


tensor([1., 1., 1., 1.], requires_grad=True)
tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [41]:
x = torch.ones(4,requires_grad=True)
print(x)

for epoch in range(3):
    y = x*3
    y = y.sum()
    y.backward()
    print(x.grad)
    x.grad.zero_() #flush gradients


tensor([1., 1., 1., 1.], requires_grad=True)
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


BACKPROPAGATION